root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o /app/server ./cmd"
  bin = "/app/server"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["vendor", "tmp", ".git"]
  delay = 1000

[log]
  time = true
